<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 */
class Event extends Model
{
    protected $table = 'events';

    public $timestamps = false;

    protected $fillable = [
        'id',
        'player_id',
        'game_id',
        'team_id',
        'type_event_id',
        'time'
    ];

    protected $guarded = [];


    


    public function typeEvent()
    {
        return $this->belongsTo(TypeEvent::class);
    }

    public function player(){
        return $this->belongsTo(Player::class);
    }

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public static function create(array $attributes = [])
    {

        $model = parent::create($attributes);


        return $model->load('typeEvent','player','team');
    }

    public function update(array $attributes = [], array $options = [])
    {


         parent::update($attributes, $options);

        $this->load('typeEvent');

        return $this;
    }
    
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }


   
    public function dataEventCreate()
    {
        $game_id = request()->get('game_id');
        $game = Game::find($game_id);

        $data = [];
        $data['teams'][] = $game->team_l->load('players');
        $data['teams'][] = $game->team_v->load('players');

        $data['types_events'] = TypeEvent::all();

        return $data;
        # code...
    }
    
}