<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 */
class Favorite extends Model
{
    protected $table = 'favorites';

    public $timestamps = false;

    protected $fillable = [
        'table_id',
        'table_name',
        'user_id'
    ];

    protected $guarded = [];

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function addFavorite(){
        $inputs = request()->all();

        $parms  = [
            'user_id' => Auth::guard('api')->user()->id,
            'table_id' => $inputs['table_id'],
            'table_name' => $inputs['table_name']
        ];

        $favorite = Favorite::create($parms);

        return $favorite;
    }

    
        
}