<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 */
class Player extends Model
{
    protected $table = 'players';

    public $timestamps = true;

    protected $fillable = [
        'id',
        'name',
        'nick',
        'birth_date',
        'number',
        'height',
        'weight',
        'position_id',
        'photo_id'
    ];

    protected $with = ['photo'];


    protected $guarded = [];

    public function photo(){
        return $this->belongsTo(Image::class);
    }

    public function teams(){
        return $this->belongsToMany(Team::class);
    }

    public function getTeamAttribute(){
         return $this->teams()->wherePivot('current',1)->first();
    }

    public function position(){
        return $this->belongsTo(Position::class);
    }

    public function events(){
        return $this->hasMany(Event::class);
    }

    

    public static function create(array $attributes = [])
    {


        $model = parent::create($attributes);

        $model->addPlayer($attributes);


        return $model;
    }

    public function update(array $attributes = [], array $options = [])
    {

        $model =  parent::update($attributes, $options);

        return $model;
    }
    
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function addPlayer($attributes){
        
        if( ! empty($attributes['team_id']) ){
            $this->teams()->attach($attributes['team_id']);
        }

        $this->team;
    }

    public function countGoals(){
        $event = TypeEvent::where('name','Gol')->first();
        return $this->countGoals = $this->events()->where('type_event_id',$event->id)->count();
    }

    public function countRed(){
        $event = TypeEvent::where('name','Roja')->first();
        return $this->countRed = $this->events()->where('type_event_id',$event->id)->count();
    }

    public function countYellow(){
        $event = TypeEvent::where('name','Amarilla')->first();
        return $this->countYellow = $this->events()->where('type_event_id',$event->id)->count();
    }

    public function countAssistance(){
        $event = TypeEvent::where('name','Asistencia')->first();
        return $this->countAssistence = $this->events()->where('type_event_id',$event->id)->count();
    }

    public function profile(){
        $this->countGoals();
        $this->countYellow();
        $this->countAssistance();
        $this->countRed();
        $data = $this->load('photo','position','events');
        
        return $data;
    }

    public function pageHomePlayers(){
        return self::get();
    }
}