<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 */
class Position extends Model
{
    protected $table = 'positions';

    public $timestamps = true;

    protected $fillable = [
        'name'
    ];

    protected $guarded = [];

    public static function create(array $attributes = [])
    {


        $model = parent::create($attributes);


        return $model;
    }

    public function update(array $attributes = [], array $options = [])
    {

        $model =  parent::update($attributes, $options);


        return $this;
    }
    
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}