<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Paise
 */
class TypeEvent extends Model
{
    protected $table = 'types_events';

    public $timestamps = false;

    protected $fillable = [
        'id',
        'name',
        'icon'
    ];

    protected $guarded = [];

    public static function create(array $attributes = [])
    {


        $model = parent::create($attributes);


        return $model;
    }

    public function update(array $attributes = [], array $options = [])
    {

        $model =  parent::update($attributes, $options);

        return $model;
    }
    
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}